# Real values should be stored in AWS secrets manager and synced with external secrets operator.
apiVersion: v1
kind: Secret
metadata:
  name: document-processing-secrets
  namespace: document-processing
type: Opaque
stringData:
  RABBITMQ_URL: amqps://REPLACE_USER:REPLACE_PASSWORD@REPLACE_AMAZON_MQ_ENDPOINT:5671/%2F
  REDIS_URL: rediss://REPLACE_ELASTICACHE_ENDPOINT:6379/0
